name: Deploy Fortress

on:
  push:
    branches: [main]
    paths: ['site/**', 'stackramp.yaml']
  pull_request:
    paths: ['site/**', 'stackramp.yaml']
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: bobbydeveaux/stackramp/.github/workflows/platform.yml@main
    secrets: inherit
